'use client';
import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';

type Service = { id?: string; name: string; description: string; status: 'operational'|'degraded'|'outage'|'maintenance'; uptime: string; latency: string; icon: string };
const fallback: Service[] = [
{name:'Website',description:'Anime Cloud customer website',status:'operational',uptime:'99.99%',latency:'42 ms',icon:'◈'},
{name:'Control Panel',description:'Server management dashboard',status:'operational',uptime:'99.98%',latency:'58 ms',icon:'⌘'},
{name:'Minecraft Hosting',description:'Game server infrastructure',status:'operational',uptime:'99.97%',latency:'71 ms',icon:'▣'},
{name:'VPS Hosting',description:'Virtual private servers',status:'operational',uptime:'99.99%',latency:'36 ms',icon:'◆'},
{name:'Payment Gateway',description:'Payments and checkout services',status:'operational',uptime:'99.95%',latency:'83 ms',icon:'₹'},
{name:'Mail Hosting',description:'Transactional and hosted email',status:'operational',uptime:'99.96%',latency:'66 ms',icon:'✉'},
{name:'API',description:'Public and internal APIs',status:'operational',uptime:'99.99%',latency:'39 ms',icon:'⌁'},
{name:'Discord Bot',description:'Anime Cloud community bot',status:'operational',uptime:'99.98%',latency:'51 ms',icon:'◉'}];
const labels:any={operational:'Operational',degraded:'Degraded Performance',outage:'Major Outage',maintenance:'Maintenance'};
export default function Home(){
 const [services,setServices]=useState<Service[]>(fallback); const [updated,setUpdated]=useState(new Date()); const [logoUrl,setLogoUrl]=useState('');
 useEffect(()=>{let servicesChannel:any;let settingsChannel:any; const load=async()=>{const {data}=await supabase.from('status_services').select('*').order('sort_order');if(data?.length)setServices(data.map((x:any)=>({...x,uptime:`${Number(x.uptime).toFixed(2)}%`,latency:`${x.latency_ms} ms`,icon:fallback.find(f=>f.name===x.name)?.icon||'◈'})));setUpdated(new Date());};const loadLogo=async()=>{const {data}=await supabase.from('status_settings').select('logo_url').eq('id',true).maybeSingle();if(data)setLogoUrl(data.logo_url||'');};load();loadLogo();servicesChannel=supabase.channel('status-services').on('postgres_changes',{event:'*',schema:'public',table:'status_services'},load).subscribe();settingsChannel=supabase.channel('status-settings').on('postgres_changes',{event:'*',schema:'public',table:'status_settings'},loadLogo).subscribe();return()=>{supabase.removeChannel(servicesChannel);supabase.removeChannel(settingsChannel)};},[]);
 const degraded=services.filter(s=>s.status==='degraded'||s.status==='maintenance').length; const outage=services.some(s=>s.status==='outage'); const overall=outage?'Major Service Outage':degraded?'Minor Service Degradation':'All Systems Operational';
 const Brand=()=> <div className="brand">{logoUrl?<img className="navLogo" src={logoUrl} alt="Anime Cloud"/>:<span className="brandMark">A</span>}<span>ANIME <b>CLOUD</b></span></div>;
 return <main><nav className="nav"><Brand/><div className="navLinks"><a href="#services">Services</a><a href="#incidents">Incidents</a><a href="#maintenance">Maintenance</a><a className="admin" href="/admin">Admin</a></div></nav><section className="hero"><div className="glow"/><p className="eyebrow">ANIME CLOUD · SYSTEM STATUS</p><h1>Infrastructure,<br/><span>without the guesswork.</span></h1><p className="sub">Real-time visibility into every Anime Cloud service. Changes are delivered instantly.</p></section><section className="overall"><div><span className={`pulse ${outage?'outage':''}`}/><div><strong>{overall}</strong><small>Last checked {updated.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div></div><span className="refresh">● Live · Realtime</span></section><section id="services" className="section"><div className="sectionHead"><div><p className="eyebrow">LIVE MONITORING</p><h2>Services</h2></div><span className="count">{services.length} services</span></div><div className="grid">{services.map(s=><article className="card" key={s.id||s.name}><div className="cardTop"><div className="icon">{s.icon}</div><span className={`status ${s.status}`}>● {labels[s.status]}</span></div><h3>{s.name}</h3><p>{s.description}</p><div className="metrics"><div><small>24H UPTIME</small><b>{s.uptime}</b></div><div><small>LATENCY</small><b>{s.latency}</b></div></div><div className="bars">{Array.from({length:30},(_,i)=><i key={i} className={(s.status!=='operational'&&i>25)?'warn':''}/>)}</div></article>)}</div></section><section id="incidents" className="section split"><div><p className="eyebrow">INCIDENT HISTORY</p><h2>Recent incidents</h2></div><div className="timeline"><div className="incident"><span className="dot resolved"/><div><b>Live incident feed</b><p>Realtime database updates enabled</p><small>New incident and service-status changes can be connected to this feed.</small></div><em>Live</em></div></div></section><section id="maintenance" className="maintenance"><div><p className="eyebrow">UPCOMING</p><h2>Scheduled maintenance</h2><p>Maintenance events can be published from the admin console and displayed here in real time.</p></div><div className="calendar"><span>LIVE</span><b>↻</b><small>REALTIME</small></div></section><footer><Brand/><p>Transparent status. Reliable infrastructure.</p><span>Supabase Realtime connected</span></footer></main>;
}