'use client';
import { useEffect, useState } from 'react';
import './admin.css';
import { supabase } from '../../lib/supabase';

type Service={id:string;name:string;description:string;status:string;monitor_url:string|null;monitor_enabled:boolean;expected_status:number};
export default function Admin(){
 const [session,setSession]=useState<any>(null); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [services,setServices]=useState<Service[]>([]); const [msg,setMsg]=useState(''); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!supabase)return; supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false);}); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(session)load();},[session]);
 async function load(){if(!supabase)return;const {data,error}=await supabase.from('status_services').select('id,name,description,status,monitor_url,monitor_enabled,expected_status').order('sort_order');if(error)setMsg(error.message);else setServices(data||[]);}
 async function login(){if(!supabase)return;setMsg('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message);}
 async function save(s:Service){if(!supabase)return;const {error}=await supabase.from('status_services').update({status:s.status,monitor_url:s.monitor_url||null,monitor_enabled:s.monitor_enabled,expected_status:Number(s.expected_status),updated_at:new Date().toISOString()}).eq('id',s.id);setMsg(error?error.message:'Saved — public status updates in real time.');if(!error)load();}
 function edit(id:string,key:string,value:any){setServices(xs=>xs.map(s=>s.id===id?{...s,[key]:value}:s));}
 if(loading)return <main className="adminPage"><section className="adminWrap"><p className="muted">Loading authentication…</p></section></main>;
 if(!session)return <main className="adminPage"><section className="adminWrap"><p className="eyebrow">ADMIN AUTHENTICATION</p><h1>Anime Cloud Admin</h1><p className="muted">Sign in with your Supabase admin account.</p><div className="adminCard login"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button className="primary" onClick={login}>Sign in</button>{msg&&<p className="error">{msg}</p>}</div></section></main>;
 return <main className="adminPage"><nav className="nav"><div className="brand"><span className="brandMark">A</span><span>ANIME <b>CLOUD</b></span></div><div><button onClick={()=>supabase?.auth.signOut()}>Logout</button> <a href="/" style={{color:'#aaa',textDecoration:'none',marginLeft:12}}>← Public status</a></div></nav><section className="adminWrap"><p className="eyebrow">ADMIN CONSOLE</p><h1>Status management</h1><p className="muted">Authenticated admin controls for live service status and automatic uptime monitoring.</p><div className="adminCard"><h2>Services & Monitoring</h2>{services.map(s=><div className="row" key={s.id}><div><b>{s.name}</b><small>{s.description}</small><input value={s.monitor_url||''} onChange={e=>edit(s.id,'monitor_url',e.target.value)} placeholder="https://service.example.com"/></div><div className="controls"><select value={s.status} onChange={e=>edit(s.id,'status',e.target.value)}><option value="operational">Operational</option><option value="degraded">Degraded</option><option value="outage">Major outage</option><option value="maintenance">Maintenance</option></select><label><input type="checkbox" checked={s.monitor_enabled} onChange={e=>edit(s.id,'monitor_enabled',e.target.checked)}/> Monitor</label><button className="primary" onClick={()=>save(s)}>Save</button></div></div>)}{msg&&<p className={msg.startsWith('Saved')?'success':'error'}>{msg}</p>}</div></section></main>;
}