'use client';
import { useEffect, useState } from 'react';
import './admin.css';
import { supabase } from '../../lib/supabase';

type Service={id:string;name:string;description:string;status:string;monitor_url:string|null;monitor_enabled:boolean;expected_status:number;sort_order?:number};
export default function Admin(){
 const [session,setSession]=useState<any>(null); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [services,setServices]=useState<Service[]>([]); const [msg,setMsg]=useState(''); const [loading,setLoading]=useState(true); const [newName,setNewName]=useState(''); const [newDescription,setNewDescription]=useState(''); const [logoUrl,setLogoUrl]=useState(''); const [logoFile,setLogoFile]=useState<File|null>(null); const [logoBusy,setLogoBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false);}); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(session){load();loadLogo();}},[session]);
 async function load(){const {data,error}=await supabase.from('status_services').select('id,name,description,status,monitor_url,monitor_enabled,expected_status,sort_order').order('sort_order');if(error)setMsg(error.message);else setServices(data||[]);}
 async function loadLogo(){const {data,error}=await supabase.from('status_settings').select('logo_url').eq('id',true).maybeSingle();if(!error)setLogoUrl(data?.logo_url||'');}
 async function login(){setMsg('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message);}
 async function save(s:Service){const {error}=await supabase.from('status_services').update({status:s.status,monitor_url:s.monitor_url||null,monitor_enabled:s.monitor_enabled,expected_status:Number(s.expected_status),updated_at:new Date().toISOString()}).eq('id',s.id);setMsg(error?error.message:'Saved — public status updates in real time.');if(!error)load();}
 async function addStatus(){const name=newName.trim();if(!name){setMsg('Enter a service name.');return;}const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString(36);const {error}=await supabase.from('status_services').insert({name,slug,description:newDescription.trim()||`${name} service`,status:'operational',uptime:100,latency_ms:0,sort_order:services.length+1});if(error)setMsg(error.message);else{setNewName('');setNewDescription('');setMsg('Status/service added successfully.');load();}}
 async function deleteStatus(s:Service){if(!confirm(`Delete "${s.name}"? This cannot be undone.`))return;const {error}=await supabase.from('status_services').delete().eq('id',s.id);setMsg(error?error.message:`${s.name} deleted.`);if(!error)load();}
 async function uploadLogo(){if(!logoFile){setMsg('Choose a logo image first.');return;}if(!logoFile.type.startsWith('image/')){setMsg('Logo must be an image.');return;}setLogoBusy(true);setMsg('');const ext=logoFile.name.split('.').pop()||'png';const path=`logo-${Date.now()}.${ext}`;const {error:upError}=await supabase.storage.from('anime-cloud-assets').upload(path,logoFile,{upsert:true,contentType:logoFile.type});if(upError){setMsg(upError.message);setLogoBusy(false);return;}const {data}=supabase.storage.from('anime-cloud-assets').getPublicUrl(path);const {error}=await supabase.from('status_settings').upsert({id:true,logo_url:data.publicUrl,updated_at:new Date().toISOString()});setMsg(error?error.message:'Logo updated across the status page.');if(!error){setLogoUrl(data.publicUrl);setLogoFile(null);}setLogoBusy(false);}
 async function saveLogoUrl(){const {error}=await supabase.from('status_settings').upsert({id:true,logo_url:logoUrl.trim()||null,updated_at:new Date().toISOString()});setMsg(error?error.message:'Logo URL saved.');}
 if(loading)return <main className="adminPage"><section className="adminWrap"><p className="muted">Loading authentication…</p></section></main>;
 if(!session)return <main className="adminPage"><section className="adminWrap"><p className="eyebrow">ADMIN AUTHENTICATION</p><h1>Anime Cloud Admin</h1><p className="muted">Sign in with your Supabase admin account.</p><div className="adminCard login"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button className="primary" onClick={login}>Sign in</button>{msg&&<p className="error">{msg}</p>}</div></section></main>;
 return <main className="adminPage"><nav className="nav"><div className="brand">{logoUrl?<img className="adminLogo" src={logoUrl} alt="Anime Cloud"/>:<span className="brandMark">A</span>}<span>ANIME <b>CLOUD</b></span></div><div><button onClick={()=>supabase.auth.signOut()}>Logout</button> <a href="/" style={{color:'#aaa',textDecoration:'none',marginLeft:12}}>← Public status</a></div></nav><section className="adminWrap"><p className="eyebrow">ADMIN CONSOLE</p><h1>Status management</h1><p className="muted">Create, edit, delete and monitor services. All changes sync to the public page through Supabase Realtime.</p>
 <div className="adminCard"><h2>Logo</h2><div className="logoBox">{logoUrl?<img src={logoUrl} className="logoPreview" alt="Current Anime Cloud logo"/>:<span>No logo configured</span>}<div><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>setLogoFile(e.target.files?.[0]||null)}/><button className="primary" disabled={logoBusy} onClick={uploadLogo}>{logoBusy?'Uploading…':'Upload logo'}</button></div></div><div className="logoUrl"><input value={logoUrl} onChange={e=>setLogoUrl(e.target.value)} placeholder="Or paste a public logo URL"/><button onClick={saveLogoUrl}>Save URL</button></div></div>
 <div className="adminCard"><h2>Add status / service</h2><div className="add"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Service name e.g. Website"/><input value={newDescription} onChange={e=>setNewDescription(e.target.value)} placeholder="Description"/><button onClick={addStatus}>+ Add status</button></div></div>
 <div className="adminCard"><h2>Services & Monitoring</h2>{services.length===0&&<p className="muted">No services yet. Add your first status above.</p>}{services.map(s=><div className="row" key={s.id}><div className="serviceInfo"><b>{s.name}</b><small>{s.description}</small><input value={s.monitor_url||''} onChange={e=>edit(s.id,'monitor_url',e.target.value)} placeholder="https://service.example.com"/></div><div className="controls"><select value={s.status} onChange={e=>edit(s.id,'status',e.target.value)}><option value="operational">Operational</option><option value="degraded">Degraded</option><option value="outage">Major outage</option><option value="maintenance">Maintenance</option></select><label><input type="checkbox" checked={s.monitor_enabled} onChange={e=>edit(s.id,'monitor_enabled',e.target.checked)}/> Monitor</label><button className="primary" onClick={()=>save(s)}>Save</button><button className="danger" onClick={()=>deleteStatus(s)}>Delete</button></div></div>)}{msg&&<p className={msg.includes('error')||msg.includes('failed')?'error':'success'}>{msg}</p>}</div></section></main>;
 function edit(id:string,key:string,value:any){setServices(xs=>xs.map(s=>s.id===id?{...s,[key]:value}:s));}
}